### ISSUE TITLE
Please add poetry plugin poetry-plugin-pypi-mirror to renovate docker image

### ISSUE THREAD

**Issue by nudgegoonies** [renovatebot/base-image#688]
For internal artifacts and for caching of upstream PyPI artifacts we use Artifactory.
Renovate finds and updates these artifacts with our pip.conf that points to Artifactory.

But Poetry projects fail with an error message, that internal artifacts are not found.
Poetry needs the plugin poetry-plugin-pypi-mirror and the variable POETRY_PYPI_MIRROR_URL.
Please add the plugin poetry-plugin-pypi-mirror to the poetry installation within the renovate docker image.

**Comment by viceice** [comment]
It needs a bit to bubble through to renovate

**Comment by nudgegoonies** [comment]
Thank you!
